version: '3.1'
services:
   postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
   product:
    image: albinxavier/spring-web-app
    ports:
      - "8080:9999"
    depends_on:
      - postgresqldb 
